### PR TITLE
Broke up Basic Rules into five documents

### PR DESCRIPTION
**Pull request by bleehu**
modified:   01_01_Basic_Rules.txt
	renamed:    01_02_Conditions.txt -> 01_03_Conditions.txt
	new file:   01_03_Damage_Types_and_Armor_Types.txt
	new file:   01_04_Leveling_Up.txt
	new file:   01_05_Cloaking_Rules.txt

### CODE REVIEW

**Review by Turtlelord26 — CHANGES_REQUESTED** [review]
This is excellent; I would only mention two things:
1. The Conditions file rename gives us two 03s and no 02s. Why happen? (blocker)
2. Basic is still a little gigantic. What would you say to splitting off the combat rules too? 01_06_Combat_Rules.txt? (nonblocker)

**Comment by bleehu** [comment]
How do you tell if a rule that usually happens in combat and sometimes doesn't is in basic rules or combat rules?

**Comment by Turtlelord26** [comment]
It looks like there's a natural divide where anything after line 662 is a combat rule. Are there specific rules you think would be problematic?
https://github.com/bleehu/Compound_X/blob/47c299313539a1cb0180e8b99dbbcb565b6e215e/01_01_Basic_Rules.txt#L662

**Comment by bleehu** [comment]
Nothing specific, I just have this gut feeling that Basic vs Combat is a blurry line and that ambiguity is going to lead to shuffling through things. Can I do that separation in a subsequent pull? I won't close #483 until that second pull is merged?

**Comment by Turtlelord26** [comment]
'Twas a nonblocker. We can remand further discussion to said issue.

**Review by Turtlelord26 — APPROVED** [review]

**Pull request merged**
