### PR TITLE
DoubleTap; Update 03_Feats.txt

### PR DESCRIPTION
**Pull request by 1sourcecontrol**
@trowl223 Changed DoubleTap to remove crit range, and I'm a little fuzzy on what the details are for the revision so I just wrote with regards to another free firing action, see changes.

### CODE REVIEW

**Comment by bleehu** [comment]
Can we add that this ability can't trigger itself recursively? And maybe that this effect can't be used more than once per turn per gun? So as to prevent using machine pistols to empty their mags?

**Comment by bleehu** [comment]
When we merge and delete, close Issue #63

**Comment by trowl223** [comment]
I do think @1sourcecontrol's idea that only semi-auto weapons should be able to crit should be applied to this feat. I'd like to make a motion to change the text so it reads "Only usable with Semi-Auto weapons. Not usable with . . ."

**Comment by bleehu** [comment]
Motions are for democratic organizations. You're director. You don't make motions, you make directives. You can be polite about it, but a committee would take too long to build CX. You can ask for options and opinions, but at the end of the discussion, Picard says, make it so. Not I make a motion ;)

**Comment by 1sourcecontrol** [comment]
Alright, I made the text changes. From what I understand, this feat will allow the player to make another weapon roll, correct? Not just a free automatic hit?

**Comment by 1sourcecontrol** [comment]
@trowl223 , does this feat mean that the player will get another free weapon attack roll on an Extra-Crit?
Or does the feat mean that the player does double damage when he rolls an Extra-Crit?

**Pull request merged**
