### PR TITLE
removed crit from doc proceedures and vorpal rounds.

### PR DESCRIPTION
**Pull request by bleehu**
Extra crits are apparently not a thing anymore?

 Changes to be committed:
	modified:   CharacterCreation/Class-Specific Documentation/Doctor Procedures.txt
	modified:   Items/04_00_WeaponAttachments.txt

https://github.com/bleehu/CX_Design_Guide/issues/73

### CODE REVIEW

**Comment by Turtlelord26** [comment]
Say what?

**Comment by bleehu** [comment]
It must've been removed in Combat 2.0? https://github.com/bleehu/Compound_X/blob/dev/01_02_Combat_Rules.txt#L279

**Comment by Turtlelord26** [comment]
I remember having that conversation already. 1Source removed them because he was concerned about the extra die roll necessary to distinguish crits from extra-crits, but we were of the opinion that that particualar extra roll is a fun extra roll and decided we wanted to keep extra-crits. It doesn't seem to have made it into Issue form yet, but that's fixable.

**Comment by Turtlelord26** [comment]
Vorpal wants its extra-crits back, then you're all good here.

**Pull request merged**
