### PR TITLE
Intercepting projectiles is not defusing.

### PR DESCRIPTION
**Pull request by Turtlelord26**
re #378

### CODE REVIEW

**Review by bleehu — CHANGES_REQUESTED** [review]
That seems _really_ nitpicky. Strictly speaking, using incompressible liquid to render an explosive unable to detonate is defusing it. https://en.wikipedia.org/wiki/Bomb_disposal#Projected_water_disruptors Simply intercepting a grenade would mean that it still goes off at the point of interception. The principle use of the ASPRO-S isn't just to keep the grenades away, but to stop them from going off. https://en.wikipedia.org/wiki/Trophy_(countermeasure).

**Comment by Turtlelord26** [comment]
I have to concede the point about interception, but defuse is still wrong due to common usage issues. The technically correct "render less harmful" definition mutating into nonexplosive destruction just doesn't happen in practice, by comparison with the "reach into the bomb's guts (physically, electronically, whatever) and pull out the bit that makes it go boom".
At least, as far as I have ever seen.

I have tried a different approach that uses neither term.

And also fixed the issue where the ASPRO stopped incoming legislation instead of bombs.

**Comment by bleehu** [comment]
How about "neutralizers" Which is what the Israelis call the projectiles that the TROPHY system uses?

**Comment by bleehu** [comment]
My concern is that when I hear "ammunition" I think "bullets". and this doesn't fire bullets, it shoots jets of basically hydraulic fluid.

**Comment by bleehu** [comment]
ah, nevermind. It's not worth quibbling over. If you like ammunition, let's just go with that.

**Review by bleehu — APPROVED** [review]

**Comment by Turtlelord26** [comment]
I think I've managed to sidestep the issue of what it's firing entirely, which may be for the best. If we want to specify what it's shooting, we should do so higher in the description, maybe tacked on to the "eliminates incoming explosive ordnance" first sentence.

**Review by bleehu — APPROVED** [review]
shipit!

**Pull request merged**
