### PR TITLE
added prose for the Condrich's Tough Skin ability

### PR DESCRIPTION
**Pull request by bleehu**
On branch MH/Issue-777/tough-skin
	modified:   01_04_Species_Opaleites.txt

Should close out Issue #777

### CODE REVIEW

**Review by Turtlelord26 — CHANGES_REQUESTED** [review]
This isn't just prose, you rewrote the mechanics too. I like the concept a lot, but giving an armor seems maybe too similar to the racial armor trait drones get. 
Also, the plus 40 AS alarms me - it nearly doubles any <5 level character's damage soak per turn. Not in line with other racial traits' strength, and it could make chondrich mandatory for tanks.

**Comment by rosebrallier** [comment]
@Turtlelord26 Personally, I think the APL of 1 somewhat (though not entirely) balances the rest of the trait's strength, but you have a point overall; the +40 AS should probably be nerfed.

**Comment by bleehu** [comment]
In my mind, 40 AS is one pistol round, one SMG round or half an assault rifle round. That seems sane to me. If it still seems too high, I'll nerf it.

**Review by Reveraine — COMMENTED** [review]
I think that this change is good, but probably needs to be balanced further. 
I think either the coverage amount goes down, or the armor strength does (or it needs to have no per-round regeneration, but that sounds needlessly complex). In any case, I think it is close to ready.

**Review by Turtlelord26 — APPROVED** [review]

**Pull request merged**
