### PR TITLE
Tools from Backgrounds

### PR DESCRIPTION
**Pull request by rosebrallier**
Characters gain a tool set based on their Profession. Re Issue #932

### CODE REVIEW

**Review by Turtlelord26 — APPROVED** [review]
Very hands-off approach. Totally on-board, but as a thought experiment, what would you think of putting a 'suggested tool set' on each professional background?

Slight concern that your section header Tools of the Trade shares its name with a professional background.

**Comment by rosebrallier** [comment]
> Very hands-off approach. Totally on-board, but as a thought experiment, what would you think of putting a 'suggested tool set' on each professional background?
Have at it!
 
> Slight concern that your section header Tools of the Trade shares its name with a professional background.
Oh. Yep. I agree; no idea what else to title it with yet.

**Comment by Turtlelord26** [comment]
> > Very hands-off approach. Totally on-board, but as a thought experiment, what would you think of putting a 'suggested tool set' on each professional background?
>
> Have at it!

On reflection, definitely a new issue to be considered in another PR.

**Review by Reveraine — APPROVED** [review]
What about leaving Tools of the Trade as-is here and changing the name of the professional experience?

**Pull request merged**
