### PR TITLE
Pwn pronunciation guide

### PR DESCRIPTION
**Pull request by Turtlelord26**
Unresolved from #685

### CODE REVIEW

**Comment by bleehu** [comment]
I think the hard "o" symbol might break the encoding?

**Comment by Turtlelord26** [comment]
I know it breaks ANSI but is fine in Unicode. Which are we?

**Comment by bleehu** [comment]
I guess we are unicode. Let's give it a shot! 
http://flask.pocoo.org/docs/1.0/unicode/

**Review by bleehu — APPROVED** [review]
shipit

**Pull request merged**
