### PR TITLE
Medicalize Cover Slide

### PR DESCRIPTION
**Pull request by Turtlelord26**
Some functional changes here. 
* Now does not require that you end in a space with cover, to make tracking easier for the DM.
* Now consumes two actions instead of one, to avoid slapping a huge cooldown on it.
* Now gives an evasion bonus to compensate for the above. Useful for dodging readied shots and light suppression when moving between covers.

General note on Active Feats with a cooldown of None: I gave this to a few of them, generally because I'm not concerned about multiple uses per round (in the case of cover slide, it would be really hard to do so at all. The intention is that the Cooldown: None feats still require you to have a unit of medi nanites available and off cooldown., it just doesn't then send them into any remission.

### CODE REVIEW

**Review by bleehu — CHANGES_REQUESTED** [review]
Totally agree on a cooldown of none; But I would really really like to see the cover part of the cover slide retained, as well as the one-action limit; Since moving your speed is one action, and going prone is one action, combing those in a two-action feat becomes of negligible worth.

**Comment by Turtlelord26** [comment]
Moving your speed takes two actions. Will discuss other points in person.

**Comment by Turtlelord26** [comment]
Now only uses 1 Action, but gained a cooldown to compensate. Do you still want to restrict it to ending in cover? I'm a little worried about players and DMs disagreeing on what constitutes cover.

**Comment by bleehu** [comment]
They might, but we define cover pretty well in the combat rules already, https://www.compoundx.org/docs/combat#152. I would like it to continue to require cover, but after our discussion last night, it sounds like I'm the only one. Do what you feel is right.

**Review by bleehu — APPROVED** [review]
:shipit:

**Comment by Turtlelord26** [comment]
Actually, think your demonstration of the momentum stop convinced me. What do you think of this wording?

**Pull request merged**
