### PR TITLE
added laser dampening manifold attachment

### PR DESCRIPTION
**Pull request by bleehu**
modified:   04_00_WeaponAttachments.txt

should help address Issue #504

### CODE REVIEW

**Review by Reveraine — COMMENTED** [review]
I like this attachment!
I'm not sure the explanation for how lasers function is necessary here. It might be better suited to the laser weapons document, to keep the attachment document succinct. 

I'm also not sure that it makes sense to me. If the laser is not visible, why does the muzzle glow? I think it may ask more questions than it answers. (For a layman, specifically)

**Comment by Turtlelord26** [comment]
Agree with above on prose. Mechanics seem good.

One note: shotgun fire should be spreading shot shotgun fire unless you wanted to include slugs.

**Comment by bleehu** [comment]
lasers can't use slugs?

**Comment by Turtlelord26** [comment]
Laser shotguns have spreading shot and single shot modes, like ballistic ones. Or at least they should.

**Comment by bleehu** [comment]
I think in both spread and focus fire, a shotgun pushes the kind of quick burst of energy that is likely to cause a problem with an insulating manifold.

**Review by rosebrallier — APPROVED** [review]
Looks cool, and I like the writing. Have at it!

**Pull request merged**
