### PR TITLE
added new feat: kip up

### PR DESCRIPTION
**Pull request by bleehu**
Seemed like a fairly obvious missing feat. Needed a break from craziness at work and with wedding planning. So I got a little creative.

Not sure about the prereqs, I'm not positive we're giving more useful choices for characters that have particular stats. 

The nanite cost seemed like a good rate-limiter to keep someone from abusing this to do the worm.

### CODE REVIEW

**Review by Turtlelord26 — COMMENTED** [review]
What would you think of instead having the prereq be points in Acrobatics?

**Comment by dfuchs2** [comment]
Good idea. My only question is about nanite usage. Aside from keeping people from worming, is there a reason for the ability to use them? Maybe there could be a cooldown of 3 turns in which the player receives a -20 to acrobatics or something.

**Comment by Turtlelord26** [comment]
Such a cooldown would be enough without adding any skill penalty methinks.
@dfuchs2 What if it has no baseline nanite cost, a cooldown, and a nanite payment to ignore the cooldown 1/turn.

**Comment by bleehu** [comment]
My concern with adding a cooldown longer than just 1 per round is that I'm a little concerned about giving the player too many different things to keep track of. Other than that, you're right. There isn't much reason to use nanites.

**Comment by dfuchs2** [comment]
I like @Turtlelord26's idea. The ability to choose to ignore a cooldown is an interesting idea.
Also, I agree that 3 turns is too long. Too much to keep track of. I'd be fine with it only being 1 turn. It is a feat after all. Players don't get very many of them and they shouldn't be restricted heavily.

**Comment by bleehu** [comment]
How is that? Please review! (like, hit the green review button!)

**Review by dfuchs2 — APPROVED** [review]
Looks good to me. I could definitely see myself using it if I build a high dex character. Maybe an assassin character or something.

**Pull request merged**
