### PR TITLE
Separated Combat Rules from Basic rules

### PR DESCRIPTION
**Pull request by bleehu**
Changes to be committed:
	modified:   01_01_Basic_Rules.txt
	new file:   01_02_Combat_Rules.txt
	renamed:    01_02_Damage_Types_and_Armor_Types.txt -> 01_04_Skill_DCs.txt
	renamed:    01_03_Conditions.txt -> 01_05_Conditions.txt
	renamed:    01_04_Leveling_Up.txt -> 01_06_Leveling_Up.txt
	renamed:    01_05_Cloaking_Rules.txt -> 01_07_Cloaking_Rules.txt

### CODE REVIEW

**Comment by Turtlelord26** [comment]
Now there is no 01_03?

**Comment by bleehu** [comment]
I moved the order of Skill DCs so that Damage Types would be next to Conditions, which made some conceptual sense to me. https://github.com/bleehu/Compound_X/blob/MH/Issue-473/Break-up-basic-rules/01_03_Skill_DCs.txt

**Comment by Turtlelord26** [comment]
Ah, I see. This is the problem I was almost seeing.

    renamed: 01_02_Damage_Types_and_Armor_Types.txt -> 01_04_Skill_DCs.txt

**Review by Reveraine — APPROVED** [review]
Ship It!

**Review by Turtlelord26 — CHANGES_REQUESTED** [review]
Please do not ship it without resolving the duplicate filenames.

**Comment by Turtlelord26** [comment]
image

**Review by Turtlelord26 — APPROVED** [review]

**Comment by bleehu** [comment]
This should close Issue #473

**Pull request merged**
