### PR TITLE
Fix Issue #174.

### PR DESCRIPTION
**Pull request by bleehu**
clarified ambiguity in class feat acquisition elucidated in Issue #174. Please note added reference to Skills in Basic Rules doc instead of having a rule oddly stuck in the Classes doc.

### CODE REVIEW

**Review by Turtlelord26 — CHANGES_REQUESTED** [review]
Skills doc reference noted and appreciated.

New text doesn't scan very well. We have line 6 referencing class feat initial acquisition, then talk about skills before we get back to class feats. 
Would like to move skills wholly before or after class feat text. 
Also the reference to "level 5 ..." in line 10 should be a reference to "level 10 and every 5 levels thereafter" or just "levels 10, 15, and 20".

**Comment by 1sourcecontrol** [comment]
So, I don't understand. Are we doing this change twice #193 because I forgot to link the issue, or do you want to redo what I was PR'ing?

**Comment by bleehu** [comment]
@1sourcecontrol If I'm seeing this right, the two changes are next to each other but not the same? This change is for class feats, the one I requested in 193 is for the sentence about skills.

**Comment by 1sourcecontrol** [comment]
image

We state a lot of the same things, just in two different locations.

**Comment by 1sourcecontrol** [comment]
I'll save us more trouble and just merge my stuff, then you can figure out the conflict however you like

**Comment by bleehu** [comment]
Especially interested in 1Sourcecontrol's feedback on language at the top. I don't want to squash your work but I think I did this time. Let me know if you like your way better.

**Review by 1sourcecontrol — APPROVED** [review]
can you put the line 11 "RP / Using Skills" section in quotes or something? It may be confusing to the player if we don't indicate that the text is in one block (FYI it was a little confusing to me).

Otherwise, looks great! I am more concerned with the "at level 5 gain class feat" stuff, and that looks good now. So we kool.

Feel free to ship if you agree with me about the above and add the necessary change! :)

**Comment by 1sourcecontrol** [comment]
>can you put the line 11 "RP / Using Skills" section in quotes or something? It may be confusing to the player if we don't indicate that the text is in one block (FYI it was a little confusing to me).

Michael, you merged without making the change or saying anything against it!

**Comment by 1sourcecontrol** [comment]
@bleehu

**Pull request merged**
