### PR TITLE
Constructor Drone First Trait

### PR DESCRIPTION
**Pull request by dfuchs2**

### CODE REVIEW

**Comment by bleehu** [comment]
Don't forget to put a quick synopsis of the changes you made in the commit log, that'll help @Turtlelord26 make change logs for when your work ships to RC and Play later!

**Review by bleehu — APPROVED** [review]
I like it! I kinda miss how security drones aren't big and bulky as a species anymore, and I'm glad you put that back in as at least an option!

**Review by Turtlelord26 — COMMENTED** [review]
This trait looks like two traits stapled together: the attribute modifiers and the skill modifiers. I would wonder if we could separate them (and maybe swap the flat skill bonus to an Advantage roll).
Design question @Reveraine: Are attribute modifiers in species traits a thing we can/want to do?

**Comment by Reveraine** [comment]
To write down what I said in stand-up, so we do not forget, attribute modifiers are unique to sub-species rather than actual traits.

**Comment by dfuchs2** [comment]
Should I keep it as it is, or should I change this trait up a bit? I'm open to changing it if it makes it fit the current design better.

**Comment by Turtlelord26** [comment]
The only change we require is that the attribute modifiers leave the trait and become subspecies passives (see other species files for format).

I think the rest of it is a good trait as it stands. I would personally consider swapping out the +20 for Advantage on those rolls, but that's your call.

**Comment by bleehu** [comment]
Linking Issue #554

**Pull request merged**
