### PR TITLE
Mh/issue 578/gun rule item doc

### PR DESCRIPTION
**Pull request by bleehu**
whoops! I need to rebase this to be from the dev branch. I must've branched this off of the dog superbranch.

### CODE REVIEW

**Comment by bleehu** [comment]
Each weapon document currently has a paragraph or so about the rules of their specific weapon types. Things like default reload action time, default suppression level, etc. I intentionally left those there unless otherwise told to move them.

**Comment by bleehu** [comment]
Should handle issue #578

**Comment by Turtlelord26** [comment]
Things like default stats are acceptable rules to leave in item docs methinks.

**Review by rosebrallier — APPROVED** [review]
Wheeeeeee

**Pull request merged**
