### PR TITLE
Turtlelord26 Reflavored Engineer Energy into Potential

### PR DESCRIPTION
**Pull request by Turtlelord26**
#635
To avoid balance conflict with Energy for Cloaks and Shields.

Some work done in the Engineer Processes document for #593

### CODE REVIEW

**Review by Reveraine — APPROVED** [review]
Excellent!
Thanks for spell-checking along the way! I quite enjoy the flavor text about Potential and Grey goo plagues.

**Review by bleehu — APPROVED** [review]
shipit!

**Comment by Turtlelord26** [comment]
@bleehu, can I get an explicit go/no-go on the change to the Overbuilt class feat?

**Comment by bleehu** [comment]
Explicit shipit.

**Comment by Turtlelord26** [comment]
Thanks!

**Pull request merged**
