### PR TITLE
Added glow sticks to items

### PR DESCRIPTION
**Pull request by bleehu**
Reading the DnD dungeons that I got for Christmas pointed out a couple of items that we could have but that we don't yet.

Also rearranged consumable items to be more alphabetically ordered.

### CODE REVIEW

**Comment by Turtlelord26** [comment]
I don't see any new items?

**Comment by bleehu** [comment]
bugger all. Last change didn't make it into the commit apparently.

**Comment by bleehu** [comment]
@Turtlelord26 How's that?

**Comment by Turtlelord26** [comment]
Cyalume's an old trademark but it is a trademark. Can we use it in a for-profit endeavor?
(I am not remotely familiar with trademark legalities)

**Comment by bleehu** [comment]
I'm not either. Better safe than sorry, but that's an astronomical long shot. I don't think Michael Rauhut is gonna file suit 'cause we used the name of his compound in the 40th line of our twentieth document. I'll change it just to be safe.

**Comment by bleehu** [comment]
@Turtlelord26 How's that?

**Review by Turtlelord26 — APPROVED** [review]
👍

**Pull request merged**
