### PR TITLE
added gluon rounds

### PR DESCRIPTION
**Pull request by bleehu**
Basically level 10 armor piercing rounds.

### CODE REVIEW

**Comment by bleehu** [comment]
Stats totally negotiable

**Review by Turtlelord26 — CHANGES_REQUESTED** [review]
I'm mildly concerned, aesthetically, about absolutes like "inseparable" and "no matter what it hits". The mechanics seems reasonable.

It's not clear to me whether that last line is saying that gluon rounds bypass AS.

**Comment by bleehu** [comment]
That's not actually Aesthetic. It's real-world science. I'm having a little trouble finding the specific formula, since I got the idea from a lecture at UW. But it turns out that the strong atomic force between to mated gluons increases geometrically the further apart they're pulled. With no known limit. https://en.wikipedia.org/wiki/Glueball. Now creating a glueball would take unrealistic amounts of energy, but significantly less than it would take for FTL travel.

**Comment by Turtlelord26** [comment]
Strong force is breakable though. Yes, it does take more and more force to pull strongly interacting particles farther apart, but at some distance the strong force suddenly drops to ~zero~ negligible levels. Otherwise fission would not be possible.

Parts of my hightech document imply some control over the strong force, hence I'm not concerned about constructing them.

Also, more practically, re "no matter what it hits", if I shoot a glueball bullet at a glueball shield, which wins?

**Comment by Turtlelord26** [comment]
Post discussion, now asking only for a clarity pass on the armor bypassing mechanic.

**Review by Turtlelord26 — APPROVED** [review]
Shipit

Query: I thought you wanted to try triple AS damage first?

**Pull request merged**
