### PR TITLE
added Defuse and Jam DC to the Engineer's IED process

### PR DESCRIPTION
**Pull request by bleehu**
To address Issue #324

### CODE REVIEW

**Comment by Turtlelord26** [comment]
Where it says proxy, do you mean proximity?

**Comment by bleehu** [comment]
Indeed I did. Also I should have added some more detail on proximity detonation as well.

**Review by Turtlelord26 — APPROVED** [review]
[Stealth statement subject to revision in the far future]

Looks good 👍 

Though isn't that bit about concealing the IED the kind of rules-embedded tactical advice you've spoken against elsewhere?.

**Comment by bleehu** [comment]
It borders on it, but offers some tactical constraints by stating which specific stealth roll is to be used.

**Pull request merged**
