### PR TITLE
Bump Play to version 0.1.5

### PR DESCRIPTION
**Pull request by bleehu**
Let's set sail and shipit!

Shipit

### CODE REVIEW

**Review by Reveraine — APPROVED** [review]
Looks good to me. I really appreciate the clarification, and the additional rules. It will be really nice to play out of play again =)

**Review by Turtlelord26 — CHANGES_REQUESTED** [review]
Changes by File

## Basic Rules

- Combat stat bonus rules moved to Combat Rules, nonfunctional, ✔️
- Skill rule clarification on level 1, functional and tested ✔️
- Made critical rules for skill checks explicit, functional but has been very tested ✔️

## Combat Rules

- Made Initiative rules explicit, functional, tested ✔️
- Clarification to how accuracy limits work, nonfunctional ✔️
- Misc range-related rules moved here from weapon docs, nonfunctional ✔️
- Clarity-focused wording updates to various sections of Melee Combat are nonfunctional ✔️
- Melee 2.1 Accuracy Update: altered calculation of Accuracy for melee attacks. Functional. Tested. ✔️
- Melee 2.1 Introduction of Guard as a roll. This note to include Guard exceptions listed in individual melee weapon descriptions. Functional. Essentials Tested. ✔️
- Melee 2.1 changes "Hitting what you intend" from a 'must' to a 'may'. Technically a functional change, but pretty small. I give it a ✔️
- Melee 2.1 redesign of former blunt damage type into "Blunt Force" rule. Now damages based on STR component of weapon damage, instead of a flat amount. Functional, Untested. ❌
- Melee 2.1 Nonlethal damage rework. Now imposes accuracy penalty, may be declared on any attack. Drops targets unconscious. Functional change. Untested. ❌
- Melee 2.1 Maneuver Reworks condensed to one line because they're all functional and untested. ❌
- Melee 2.1 Weapon Size stat added. Nonfunctional, used by other functional rules. ✔️
- Melee 2.1 Rules for Two-handed attacks. Functional. Untested. ❌
- Rules moved from Melee and thrown doc to here, nonfunctional. ✔️
- Free Actions and Reactions defined formally. A functional change, but as we've been doing it this way the whole time it's been tested. ✔️
- Reactions rate-limited to 3 per round per character. Functional. untested. ❌
- Clarity pass on Critical Hit section's wording. Nonfunctional ✔️
- Extra-crits reintroduced. Functional change to the rules, but a well-tested one. People like these. ✔️
- Melee 2.1 Firing into Melee Combat rule: added chance to hit unintended targets. Functional. Untested. ❌
- Rules moved here from Armor doc. Nonfunctional. ✔️
- New Stabilization rules. Now explicitly allows and requires use of Repair instead of Medicine on robotic targets. Allows use of Med/Repair kits. Constrains assistance. Functional, tested. ✔️

## Damage Types

- Removal of unnecessary and outdated prose. Nonfunctional ✔️
- Removal of "melee" damage type, see Melee 2.1 blunt damage redesign note above. ✔️

## Glossary

- Added terms: Round, Reaction, Turn. Not a functional change but a welcome clarification. ✔️

## Feats

- Akimbo updated to support Melee weapons. Functional - does add new mechanics. Untested. ❌
- New Feat: Improvisational Brawler. Allows use of Expertise bonuses on improvised weapons. Functional. Untested. ❌
- New feat: Return to Sender. Allows uncooked grenades to be thrown back. Functional, untested. ❌
- New Expertise Feats for (almost) all weapon types. These are functional changes replacing a badly implemented earlier iteration, but they are not tested enough to be cleared into play. ❌
- New Active feat: Kip-up. Allows prone->standing as a Free Action. Cool new cooldown-or-payment decision tension mechanic. Functional. Untested. ❌

## Doctor Procedures, Engineer Procedures

- Rules text clarifications re Turn and Round. Not functional changes, but excellent clarity. ✔️
- Engineer Procedure Sup it Up duration increased from 8 Rounds to Infinite. Owing to the particular text of this ability and reliance on DM discretion, I rule it acceptable despite untestedness. ✔️

## Old Character Creation Readme

-It's dead, Jim. ✔️

## Attachments

- New Attachment - Overcharged Laser Capacitors. Functional. Untested, but very mathed. I have a clarity concern that I have Issued, so I think it can have a ✔️

## Various weapons docs

- Rules text moved to Combat rules. Nonfunctional. ✔️
- Grenade launcher skill requirement increased from 10 to 12 (what is this, an Blizzard patch note?). Functional, Untested. But also, if you want a grenade launcher and are level 5+, you probably have the extra 2 points. I rule ✔️
- Missile Launcher save gets typed to Shock. Functional, necessary. ✔️

## Melee and Thrown

- Whip description updated to interface with new maneuvers. Nonfunctional. ✔️
- Added mechanic to grenades to allow a short dive on succeeding a high Reflex save. Functional, tested. ✔️
- Nonfunctional damage type notes as recorded in the pull of 0.1.5 from dev to RC. ✔️


## Armors

- Rules text moved to Combat rules, nonfunctional ✔️

## Items

- New Items: (Military) Water Visors. Functional, Untested. ❌
- New Items: Datapad, Binoculars, Industrial Paint, Adhesive Foam, Solvent, Storage Crates, Canteen, Firestarter, Shovel, Vibroshovel. Functional, small. I would rule ✔️
- New Item: False Fauna. Functional. Sufficiently tested - fairly certain not broken. ✔️
- New Item: Universal Translator. Implies language mechanics we don't have yet. Functional. Untested. ❌

## Readme

- Version number bumped from 0.1.3 to 0.1.5. This is a highly functional change, and I'm not sure it received enough testing in our last few games.

**Comment by Turtlelord26** [comment]
Will amend my review in the next few days with any changes from that reversion.

**Comment by Turtlelord26** [comment]
Actually, right now, so that the 0.1.6->RC PR can move forward.

**Review by Turtlelord26 — CHANGES_REQUESTED** [review]
Changes by File

## Basic Rules

- Combat stat bonus rules moved to Combat Rules, nonfunctional, ✔️
- Skill rule clarification on level 1, functional and tested ✔️
- Made critical rules for skill checks explicit, functional but has been very tested ✔️
- Added Rolling the Average, nonfunctional but functional where used by other rules. ✔️

## Combat Rules

- Made Initiative rules explicit, functional, tested ✔️
- Clarification to how accuracy limits work, nonfunctional ✔️
- Misc range-related rules moved here from weapon docs, nonfunctional ✔️
- Clarity-focused wording updates to various sections of Melee Combat are nonfunctional ✔️
- Melee 2.1 Accuracy Update: altered calculation of Accuracy for melee attacks. Functional. Tested. ✔️
- Melee 2.1 Introduction of Guard as a roll. This note to include Guard exceptions listed in individual melee weapon descriptions. Functional. Essentials Tested. ✔️
- Melee 2.1 changes "Hitting what you intend" from a 'must' to a 'may'. Technically a functional change, but pretty small. I give it a ✔️
- Melee 2.1 redesign of former blunt damage type into "Blunt Force" rule. Now damages based on STR component of weapon damage, instead of a flat amount. Functional, Untested. ❌
- Melee 2.1 Nonlethal damage rework. Now imposes accuracy penalty, may be declared on any attack. Drops targets unconscious. Functional change. Untested. ❌
- Melee 2.1 Maneuver Reworks condensed to one line because they're all functional and untested. ❌
- Melee 2.1 Weapon Size stat added. Nonfunctional, used by other functional rules. ✔️
- Melee 2.1 Rules for Two-handed attacks. Functional. Untested. ❌
- Rules moved from Melee and thrown doc to here, nonfunctional. ✔️
- Free Actions and Reactions defined formally. A functional change, but as we've been doing it this way the whole time it's been tested. ✔️
- Reactions rate-limited to 3 per round per character. Functional. untested. ❌
- Clarity pass on Critical Hit section's wording. Nonfunctional ✔️
- Extra-crits reintroduced. Functional change to the rules, but a well-tested one. People like these. ✔️
- Melee 2.1 Firing into Melee Combat rule: added chance to hit unintended targets. Functional. Untested. ❌
- Rules moved here from Armor doc. Nonfunctional. ✔️
- New Stabilization rules. Now explicitly allows and requires use of Repair instead of Medicine on robotic targets. Allows use of Med/Repair kits. Constrains assistance. Functional, tested. ✔️

## Damage Types

- Removal of unnecessary and outdated prose. Nonfunctional ✔️
- Removal of "melee" damage type, see Melee 2.1 blunt damage redesign note above. ✔️

## Movement: Microgravity

-Added. Functional. Untested. ❌

## Classes

- Added Melee weapon size-based proficiencies to classes. Functional.
- Added baseline skill points to gunslinger. Functional. Not Tested. However, it's symmetrical with other classes, and will be tested in the class metadata project soon. I'd let it ship but will hear other opinions. ❓
- Added some more baseline skill points to Assassin and Berserker as well. See above.

## Glossary

- Added terms: Round, Reaction, Turn. Not a functional change but a welcome clarification. ✔️

## New Player Walkthrough

- Added. Occupies an interesting space in the functional change continuum, since it doesn't affect play but does affect players. It probably shouldn't go to Play until the missing sections are complete. ❌

## Feats

- Akimbo updated to support Melee weapons. Functional - does add new mechanics. Untested. ❌
- New Feat: Improvisational Brawler. Allows use of Expertise bonuses on improvised weapons. Functional. Untested. ❌
- New feat: Return to Sender. Allows uncooked grenades to be thrown back. Functional, untested. ❌
- New Expertise Feats for (almost) all weapon types. These are functional changes replacing a badly implemented earlier iteration, but they are not tested enough to be cleared into play. ❌
- New Active feat: Kip-up. Allows prone->standing as a Free Action. Cool new cooldown-or-payment decision tension mechanic. Functional. Untested. ❌
- New feat: Juggler. Buffs use of throwing weapons. Functional. Untested. ❌
- Added melee proficiency feats. Functional. Untested, but necessary for testing and balance of melee weapons.
  Detail View: The change here is that before, any class could use any nonexotic melee weapon, but now that access is restricted by having to take feats, and the severity of the restriction is based on which class is involved.
  I would probably ship it, treating it as a classification system to use as a testing baseline, but such a course requires multiple director/producer consensus.
- Added Unarmed Combat Training feat tree. Functional, untested. ❌

## Doctor Procedures, Engineer Procedures

- Rules text clarifications re Turn and Round. Not functional changes, but excellent clarity. ✔️
- Engineer Procedure Sup it Up duration increased from 8 Rounds to Infinite. Owing to the particular text of this ability and reliance on DM discretion, I rule it acceptable despite untestedness. ✔️
- Added Whateverectomy Doctor Procedure. Functional. Untested. ❌

## Old Character Creation Readme

-It's dead, Jim. ✔️

## Attachments

- New Attachment - Overcharged Laser Capacitors. Functional. Untested, but very mathed. I have a clarity concern that I have Issued, so I think it can have a ✔️

## Various weapons docs

- Rules text moved to Combat rules. Nonfunctional. ✔️
- Grenade launcher skill requirement increased from 10 to 12 (what is this, an Blizzard patch note?). Functional, Untested. But also, if you want a grenade launcher and are level 5+, you probably have the extra 2 points. I rule ✔️
- Missile Launcher save gets typed to Shock. Functional, necessary. ✔️

## Melee and Thrown

- Whip description updated to interface with new maneuvers. Nonfunctional. ✔️
- Added mechanic to grenades to allow a short dive on succeeding a high Reflex save. Functional, tested. ✔️
- Nonfunctional damage type notes as recorded in the pull of 0.1.5 from dev to RC. ✔️
- Hand to hand reworked into Unarmed Strike. Functional, untested. ❌
- Weapons have received size stats to correspond to the new proficiencies. Nonfunctional here. ✔️
- Level 10 Plasma sword loses exotic type. Strictly speaking a functional change, and untested. But I'd really like to categorize this as part of the proficiency system and ship it. ❓

## Armors

- Rules text moved to Combat rules, nonfunctional ✔️

## Items

- New Items: (Military) Water Visors. Functional, Untested. ❌
- New Items: Datapad, Binoculars, Industrial Paint, Adhesive Foam, Solvent, Storage Crates, Canteen, Firestarter, Shovel, Vibroshovel. Functional, small. I would rule ✔️
- New Item: False Fauna. Functional. Sufficiently tested - fairly certain not broken. ✔️
- New Item: Universal Translator. Implies language mechanics we don't have yet. Functional. Untested. ❌

**Comment by bleehu** [comment]
A replacement has been made where the bump is a separate branch.

**Pull request closed without merging**
