### PR TITLE
New Crit Feat; Update 03_Feats.txt

### PR DESCRIPTION
**Pull request by 1sourcecontrol**
Added a feat to increase crit chance by 10% and extra crit chance by 5%.

What should the title be? And/or the description?
Here are a few titles (gems) I came up with:
"Lucky Mother#$%^@" - really good (jk LoL)
"Luckiest man in the whole wide world wow so amaze"
"Right Place, Right Time"
"Perfect Aim"
"All I do is win"
"Enhance my Luck, GO!"
"Lucky Strikes"
"Lucky shot"
"I'm so Lucky, lel kidz get0utTheway"
"Aim Small, Miss Small"

### CODE REVIEW

**Comment by trowl223** [comment]
Maybe 5% and 5%? I think on a crit, a 10% improvement is huge.

I'm a fan of "Aim Small, Miss Small". Anyone for "Never tell me the odds", or is that too heavy a reference?

**Comment by 1sourcecontrol** [comment]
Couple thoughts:
It is a feat, so +5%/+5% might be reasonable, but it's mostly a 5% chance to see an increase of 10/20 damage which isn't a large difference in dps. So imo, crit matters more for compounding effects, specifically nanite regen/doubletap. Without other factors, we have an average +1.5 damage taking this feat, or ~+6% damage for a 60 damage gun. if I mathed correctly.

If #56 nerfs luck mod that'll make this feat more significant and simultaneously nerf crit builds, which is a good argument for +10%/+5% imo since we won't have to worry as much about people critting on 50% or something ludicrous.

**Comment by bleehu** [comment]
Crits interact with more than just damage; as per nanite regen. I would tend toward making it small and then boosting it if it tests underpowered.

Never Tell Me The Odds is FANTASTIC!!!!

**Comment by bleehu** [comment]
What's our next step with this one?

**Comment by 1sourcecontrol** [comment]
I'm waiting for a response on #77. I'll change the text to "never tell me the odds" (even though, "Enhance my Luck, GO!" is far superior).

**Comment by trowl223** [comment]
Updated, proceed.

**Comment by trowl223** [comment]
I am reserving "Aim Small, Miss Small" for another feat then.

**Comment by 1sourcecontrol** [comment]
Merged before I could make the update! D:

**Pull request merged**
