### PR TITLE
Add Automatic Fire Concurrent d10 rules

### PR DESCRIPTION
**Pull request by dfuchs2**
Added rules for concurrent d10 automatic-fire.

### CODE REVIEW

**Comment by dfuchs2** [comment]
Also, @bleehu in https://github.com/bleehu/Compound_X/issues/605 you suggested that these rules cover rolling a jam, crit, and more than one of each or both. I noticed today that automatic fire does not have the ability to crit https://github.com/bleehu/Compound_X/blob/06533a683c7ef51931e6353a90ad7c564e9aa530/01_02_Combat_Rules.txt#L465 Is that still the correct rule?

**Comment by Reveraine** [comment]
That rule is still correct, yes.

**Comment by bleehu** [comment]
Linking Issue #605

**Review by bleehu — APPROVED** [review]
elegant, simple, shipit!

**Review by Turtlelord26 — APPROVED** [review]
👍

**Pull request merged**
