### PR TITLE
rate limited quickdraw

### PR DESCRIPTION
**Pull request by bleehu**
modified:   CharacterCreation/03_Feats.txt

### CODE REVIEW

**Review by Turtlelord26 — COMMENTED** [review]
Honestly I would say 1 weapon per turn, and we can make an exception for specifically light throwing/melee weapons (maybe 3 for those?)

**Comment by bleehu** [comment]
Two lets you draw with dual wield, and gets you close to three for light melee and throwing weapons, while maintaining simplicity.

**Comment by Turtlelord26** [comment]
Ah, I'd forgotten about dual-wielding. I'm still leery of things like being able to quickdraw your LMG and then your Flamethrower on a strong back specialist. Is there a way to have the cake and eat it too?

**Review by Turtlelord26 — APPROVED** [review]
If you can't think of one, go ahead and put this in for now and we can revisit it later if it turns out to be a balance problem.

**Comment by bleehu** [comment]
With 4 Actions a turn, shouldn't be a problem. That would be enough to aim each and fire only once.

**Pull request merged**
