### PR TITLE
Rename ha fa to action; i didn't do campaign

### PR DESCRIPTION
**Pull request by 1sourcecontrol**
also did some other various typo changes when i saw them

### CODE REVIEW

**Review by bleehu — APPROVED** [review]
I think this leads to more succinct and easier to understand rules for new players. 

I noticed you shortened the cost of the steady shot feat as well. I think that's a good change, but we probably should have made sure to document it well.

**Comment by 1sourcecontrol** [comment]
Lol woops, I definitely didn't shorten steady shot on purpose.

I'm not trying to pull a fast one

**Review by bleehu — APPROVED** [review]
spacing looks better now

**Comment by trowl223** [comment]
Honestly that Steady Shot edit seems fine to me ^_^ There is one of our random mutations guys :P

**Comment by bleehu** [comment]
I'm gonna mark it approved and merge it so we can keep moving then. Great work!

**Comment by bleehu** [comment]
@1sourcecontrol don't forget to delete the local branch to keep git tidy!

**Comment by 1sourcecontrol** [comment]
@bleehu , i'm confused. You asked me to delete it but then you deleted it?

**Comment by bleehu** [comment]
I deleted it on the website, but you probably need to do a 
`$git branch -D Rename-HA-FA-to-Action_AlexL` 
on your local machine to keep your workspace clean.

**Comment by 1sourcecontrol** [comment]
Ah, I see. Thanks! But jokes on you, I have only been doing git from GitHub.com lol not from my desktop

**Pull request merged**
