### PR TITLE
Mh/version beta 0.1.2/rc

### PR DESCRIPTION
**Pull request by bleehu**
Added Melee weapon sizes
Added Weapon Proficiency feats
Added new grappling rules
Added new melee rules
Removed Tome of Spells
Broke up Basic rules into multiple files

### CODE REVIEW

**Comment by Turtlelord26** [comment]
There's ~some~ a lot of Melee 2.1 gunk in here that hasn't been formally reviewed for merging to dev. Artifacts of trying to keep the superbranch up to date with changing file locations. I've kept track of it all and can include it in the eventual PR that puts the superbranch into dev, but I'm not sure if we should put dev into RC until such time as that is taken care of.

**Comment by bleehu** [comment]
How do I know what to yank and what to keep with melee 2.0?

**Review by Reveraine — APPROVED** [review]
Looks good to me!

**Comment by Turtlelord26** [comment]
Turns out it's surprisingly easy. Literally every commit authored by me in here shouldn't go to RC yet.

**Comment by bleehu** [comment]
... or did Rev just review it all in dev?

**Comment by Turtlelord26** [comment]
It is a surprise to me, but the particular bits of melee 2.1 that slipped in seem both to be internally consistent and to interface basically functionally with the unupdated bits of rules. I guess I would also classify it as testable, though I really am unsure about the procedural virtues of merging a portion of a project. It is possible I should have waited until the project was concluded to try to reconcile it with the new file structure, but at the time that seemed daunting. I'll drop one of my usual RC reviews below as a comment review and let you decide what to do with it.

**Review by Turtlelord26 — COMMENTED** [review]
Changes Noted by Project

# Melee 2.1
-Added explicit proficiency feats for types of melee weapon, including a handling for exotic
-Gave classes starting proficiencies for melee weapons.
-Added unarmed combat feats
-Added size categories for melee weapons
-Added two-handed damage rule for two-handed and hybrid weapons.
-Replaced hand-to-hand weapons with single Unarmed Strike, which is upgraded by unarmed combat feats.
-Added size tags to all current melee weapons.

Certainly functional changes, and I believe them to be testable, but as I wrote them we should not take only my word for it.

# Repo Reorg
-Files moving everywhere, but moving rules doesn't change them. The testable factor is players referencing them while playing or prepping CX. ✔️ 

# Delete Tome of Spells
-self-explanatory, and non-functional given the destruction of relevant classes. ✔️ 

# Dice-rolling
-Text updated to include d10 combat rolls. Nonfunctional change, clarity testable. ✔️

**Pull request merged**
