### PR TITLE
added 2 slot requirement for large munitions

### PR DESCRIPTION
**Pull request by bleehu**
Should fix Issue #373. Intentionally left antimaterial single rod shots as a single mag, as well as a few of the laser guns, which I think would have smaller batteries.

### CODE REVIEW

**Review by Turtlelord26 — CHANGES_REQUESTED** [review]
I would like the mag size note under machine guns to be copied to the Heavy weapons umbrella description.

Re. Anvil Arms XM-500 Minigun, why does this one not have large magazines?

**Comment by bleehu** [comment]
Can do, will do!

Uh, it definitely does. If I recall, that was the specific weapon that caused the gripe. https://github.com/bleehu/Compound_X/blob/83fc1c76289e7e9035b1ec1b96b8a344a0b0ae89/CharacterCreation/04_06_MachineGuns_HeavyWeps_%26_RocketLaunchers.txt#L225

**Comment by bleehu** [comment]
Whoops! That's the microgun, not the minigun...

**Comment by bleehu** [comment]
https://github.com/bleehu/Compound_X/blob/83fc1c76289e7e9035b1ec1b96b8a344a0b0ae89/CharacterCreation/04_06_MachineGuns_HeavyWeps_%26_RocketLaunchers.txt#L317

**Comment by Turtlelord26** [comment]
Touchè

**Review by Turtlelord26 — APPROVED** [review]

**Pull request merged**
