### PR TITLE
added flavor text to military background.

### PR DESCRIPTION
**Pull request by bleehu**
modified:   04_Backgrounds.txt

### CODE REVIEW

**Comment by bleehu** [comment]
Should there have been more to do here?

**Review by rosebrallier — COMMENTED** [review]
This is a great start. Personally, I'd like the flavor text to be a little more dramatic like, "When you're shot at, the fear and adrenaline still pulse through you, but then your training kicks in."
OOOOOO We could re-name it to Discipline!!!!!

**Comment by bleehu** [comment]
It is so.

**Review by rosebrallier — APPROVED** [review]
Wooo!

**Pull request merged**
