### PR TITLE
Turtlelord26 version 0.3.0 to RC

### PR DESCRIPTION
**Pull request by Turtlelord26**
And here it is, the biggest fundamental system rework of the modern CX era. What say we cut it to RC?

Comprehensive technical director review forthcoming.

### CODE REVIEW

**Review by Turtlelord26 — COMMENTED** [review]
Changes by File

## Basic Rules

-Healing Injuries section re-prosed. Nonfunctional.
-Med/Repair kit use time increased to 3 Actions. Functional. Testable. ✔️
-Removed reduced Non-Doc/Engi effectiveness with kits. Functional, testable. ✔️

## Damage Types

-Some reordering and re-prosing. Nonfunctional.

## Character sheets

-A new one! Also removed old ones.

## Creating a character

-New blurb on picking species variants. Greatly improved clarity. Nonfunctional.


## Species Overview (New file)

-Codified rules text on picking a species and subspecies. Lots of prose. Technically functional. Testable. ✔️
-An overview of each species. Nonfunctional.

## Species: Human

-Anatomy, Society, Language, Naming.
-Racial Passives: Increased linguistic ability and +2 starting stat points. Functional, testable. ✔️
-Baseline traits:
--Pitching Arm: Always considered to have Aimed for throwing weapons. Testable. ✔️
--Stubborn: Advantage on DSTs. Testable. ✔️
----Flag, few baseline traits compared to other species. 🎏
-Terran traits:
--Very Normal: Straight skill points in Deception and Persuasion. Testable ✔️
--Sixth Sense: Intuition by DM ask. Testable ✔️
-Eastern Traits:
--Endurance: No penalty for first two sprinting actions. No rate limit specified. Not testable, must know how often it can be used. ❌
--Missing second trait. Flag 🎏
-Western Traits:
--Quick Constriction: Half duration on Blind condition and advantage to resist. Testable. ✔️
--Frost-free: Half damage from Thermal, advantage on saves against cold-related sources. Testable. ✔️

## Species: Class A Security Drone

-Still called drone :(
-Anatomy, Society, Language, Naming.
-Racial Passives: 
--None. Testable ✔️. Unusual deviation from pattern, flag 🎏
--No specified starting stat points. Should be 40.
-Baseline Traits:
--Built-in Armor: Reduced movement penalties from worn armor, up to 2. Testable ✔️
--Inhuman Strength: Can store 10 Energy; can spend 10 Energy to add 10 to a Str-based skill check. Testable. ✔️
--Infrared Optical Sensor: Can swap from normal vision to 20m IR vision as a free action. Testable ✔️
--Refractory Dermal Layer: Gains 15 DR vs Lasers while above half health, penalty to Stealth. Testable ✔️
-Cinder Series Traits:
--Reusable D-Filter: Resistance (?) to Flashbangs, but incompatible with Infrared Optical Sensor Trait. Flag 🎏 on similarity to Western Quick Constriction. Not testable, needs more functional text. ❌
--Flame Retardant: Resistance to High-temperature and Plasma, but vulnerable to low-temperature. Needs to be reworded with reference to Thermal damage (or reworked to only apply to environmental effects ... once we have those). Not testable. ❌
-Cryo Series Traits:
--UV Optical Module: Can swap between regular and UV vision as a free action. Bonus to Investigate while in UV, and can see energy sources. Incompatible with IR Optical Sensor trait. Testable. ✔️
--Cold Never Bothered Me: Immune to cold-based enviromental damage. +10 stealth. Bonus to skill checks relating to microgravity movement. Big penalty to Athletics while in water and Plasma burn sticks to them much longer. This is good but it has to get an ❌ until the "Swim check" is updated to Athletics text.
-Constructor Series Traits:
--Bulky Frame: Bonus to Skill checks involving stability and penalty to Stealth. While technically testable, I would prefer better-defined text for those Skill checks and also to expand it to include Shock saves for similar conditions. ❌
--Engineering-minded: Advantage on all Jury-rig checks. Seems a little too unrestricted, but testable. ✔️🎏

## Species: Tundari

-Anatomy, Society, Language, Naming.
-Racial Passives: 
--Weakness to poisons. Testable. ✔️🎏 Flag on having only a disadvantageous passive, are we sure we want to do that?
--No specified starting stat points. Should be 40.
-Baseline Traits:
--Clawed: Adds a bleed to unarmed strikes if target is not bleeding. Testable ✔️
--Soft-footed: May roll Average on any Stealth. Much better balance than Engineering-minded. Testable ✔️
--Prehensile Tail: May roll advantage on Dex-Acrobatics and Reload checks that a tail can apply to. 1/Encounter can use Advantage on a maneuver check that a tail can apply to. Testable ✔️
--Toothed: Advantage on Intimidation immediately after meeting the target. Testable ✔️🎏 Would like better clarification of "initial Intimidation check".
-Rra'mau Traits
--Hind-claws: I think it wanted to give more movement speed? Missing functional text. ❌
--Wide-faced: 1/target, may roll Persuasion with advantage. Would like rate-limiting text such as 1/day, as once per forever seems weak and open to misinterpretation. ❌
-Sang'mau Traits
--Climbing: Advantage on Str-Athletics to climb. Testable ✔️🎏 Would prefer a defined angle at which traversal becomes "climbing".
--Powerful: +2 Carry ability, scaling bonus to unarmed strike damage. Testable ✔️🎏 The level 9 should be changed to level 10.
-Chi'mau Traits
--Climbing: Advantage on Dex-Acrobatics to climb. Error: climbing is Str-Athletics. Also Error: Repeat of Sang'mau trait. Also Error: only subspecies so far to have 3 traits. ❌
--Survivalist: Gains proficiency in Jury-rig. Error: clashes with flavor text. Would prefer proficiency in Survival. ❌
--Swimmer: Advantage on rolls to swim. Can hold breath well. Need to spell out the skill that is getting the bonus (Str-Athletics). ❌

## Species: Opaleites

-Anatomy, Society, Language, Naming.
-Racial Passives: 
--Waterbreathing: Can breath underwater, but penalty to saves vs smoke or gas.
--Compound Eyes: Penalty to "general perception" (Awareness? Spotting?) above water, but can detect movement from sides without turning head. This needs better definition of what the penalty applies to and mechanical text on the whole sides thing. Proposition: penalty to Spotting but bonus or advantage to Awareness. ❌
--40 stat points.
-Baseline Traits:
--Dark vision: Actually low-light vision. Needs a new name to not confuse the DnD players. Also needs mechanical text, but that is admittedly blocked by our lack of light level rules. ❌
--Flag 🎏 on few traits compared to Tundari and Drones.
-Mendar traits
--+2 Cha
--Colorful: Can use advantage on Perform check to be very distracting to visually perceptive targets. Testable ✔️
--No second trait: flag 🎏
-Condrich traits:
--+1 Str, +1 For
--Tough Skinned: When unarmored, has natural armor with given stats. When armored, has bonus 20 AS. The Natural armor needs to be updated to Static Armor rules. ❌
--I Smell Blood: +10 Investigate to follow a trail and for primarily olfactory investigations. Advantage on melee accuracy vs targets with Bleeds. Advantage on Spotting against targets with Bleeds. -12 to saves vs smoke or gas. Abilities disabled by water/air transition, one action to reinstate. This is testable, but I think it's just giving too many things. I anticipate memory issues. ❌
-Sea Devil Traits
--+2 Dex
--Light Dance: When in low-light or darker, enemies have -1 Accuracy. Enemies can roll a save to negate. Can be used to 'distract' with opposed skill roll. ❌
----If enemies can choose to make the roll, it's a skill check not a save. Not sure that it is worth the extra words and DM overhead for that to be a thing in the first place. Suggest removing both the seeing-through-it and the distract-them check, which doesnt have great mechanical text anyway. 
--Deep Glow: Can increase darkness to low-light in 10m radius, but +1 accuracy to hit you while active. Testable. ✔️
-Opaleite subspecies are granting state boosts. This is not in line with previously-stated goals of not requiring a subspecies, and also inconsistent with all other species. ❌

## Old species file

-deleted

## Feats

-Someone changed all the tabs to spaces 😢
-New feat: Surgical Precision. Requires 30 Medicine, increases critical range with bladed melee weapons. Testable ✔️

## Doctor Procedures, Engineer Processes

-Healing related abilities up to 2 actions to use, from 1. Testable ✔️

## Combat Rules

-Stabilization up to 3 actions from 1. Testable ✔️

## Melee Combat

-Hitting what you intend updated for static armor, now scales with target armor instead of a flat threshold of 3. Testable ✔️
-Nonfunctional wording udpates

## Armor Rules, Armors

-Static Armor update!
--All instances of armor coverage in rules text and stat blocks have been converted from a % to a number. This number directly affects enemy attack rolls without adding a second armor roll. Testable ✔️

## Items

-Wording updates to Med/Repair kit to reflect new rules from above. Nonfunctional.

**Review by Turtlelord26 — COMMENTED** [review]
To-Do list:

Red X (Will definitely impede testing):

- [x] Endurance (Easterner) requires rate-limiting text
- [x] Reusable (Cinder) D-filter needs functional text
- [x] Flame Retardant (Cinder) needs wording update referencing Thermal damage or rework.
- [x] Cold Never Bothered Me (Cryo) needs skill text update
- [x] Bulky Frame (Constructor) needs skill text update and has a proposed change
- [x] Hind'claws (Rra) needs functional text
- [x] Wide-faced could use better specified rate-limit
- [x] Climbing (Chi) has multiple issues
- [x] Survivalist (Chi) should maybe be a different skill
- [x] Swimmer (Chi) needs updated skill text
- [x] Compound Eyes (Opaleite) has multiple issues
- [x] Dark vision (Opaleite) proposed name change.
- [x] Tough Skinned (Chondrich) was missed in the static armor update, needs Coverage rework.
- [x] I Smell Blood (Chondrich): Memory concerns
- [x] Light Dance (Sea Devil): Multiple issues
- [x] Opaleite subspecies are uniquely granting stat boosts.

Flag (may impede testing):

~[ ] Few baseline traits on humans~
~[ ] No second trait for Easterners~
~[ ] Drones have no species passives~
~[ ] Reusable D-filter (Cinder) almost a copy of Rapid Constriction (Westerner)~
- [x] Engineering-minded (Constructor) seems powerful
~[ ] Tundari only have a negative racial passive~
- [x] Toothed (Tundari)) needs better functional text
~Climbing (Sang) could use more definitions~
- [x] Powerful: could use a fix to uneven scaling
~[ ] Opaleites have few baseline traits~
~[ ] Mendar have only one trait~

**Comment by bleehu** [comment]
How did I let this much slip through?

**Comment by Turtlelord26** [comment]
That's why we have the fresh eyes technique : )

**Comment by bleehu** [comment]
Suppress warnings on few traits. We can add them as time goes by.

**Comment by Turtlelord26** [comment]
Will add a couple of issues to keep track of them

Edit: Issue added, warnings suppressed.

**Review by bleehu — COMMENTED** [review]
Make sure to pull from dev to Turtlelord26-version-0.3.0 before we ship this

**Review by bleehu — APPROVED** [review]
Ship thy static armor! Yussss!!!!

**Review by Reveraine — APPROVED** [review]
Excellent! I'm excited to see these changes in-game!

**Pull request merged**
