### PR TITLE
Mh version b 0.0.7 -> RC

### PR DESCRIPTION
**Pull request by bleehu**
Still small-er than the old monstrosities we used to merge. But I still need to make sure I'm doing these more often 'cause we're gaining momentum.

### CODE REVIEW

**Comment by bleehu** [comment]
When we merge this, lets post this in the dev news slack 
changelog version Beta 0.0.7

New in version 0.0.7:
+ Races are now called Species
+ Universal translator Item
+ Engineer ASPRO-S can be hacked
+ Engineer has new Peripheral: Flamethrower
+ Engineer Drone: Cerberus now has the turret it was supposed to have all along.
+ Engineer Skill trees have been updated (several fixes)
+ Classes guide added to new player guide
+ Awareness is now a saving throw, rather than a skill
+ Changed penalty for having 1 CHA
+ Added IO ports to Glossary

**Review by Turtlelord26 — CHANGES_REQUESTED** [review]
By File and Item

#Basic Rules
-New Cha penalty - Functional Change - Testable ✔️
-Awareness Save - Functional Change - Testable ✔️

#Conditions 
-New State: Lonely - Functional Change - Testable ✔️

#Glossary 
-IO Ports - Nonfunctional Change ✔️
-Lonely - Nonfunctional Change ✔️

#New Player Walkthrough
-Document - Nonfunctional Change - Mostly Testable ❔

#Systemized Skills
-Document - Functional Change - Testable ✔️ - though slightly out of date and needs certain classes removed.

#Items 
-Universal Translator - Functional Change - Testable ✔️

Engineer Processes
-IO Spell-out - Nonfunctional Change ✔️
-Cerberus Turret Specs - Functional Change - Testable ✔️

#Readme 
-Version Bump - Nonfunctional Change ✔️
-New Director - ...Change. ✔️

It is possible we should hold off on merging the New Player Walkthrough until it is a complete document that we could ~inflict upon~ have a new player try out. Marking as change request but mostly I want to see if there's a strong opinion on the matter. Default to cutting those changes from this merge.

**Comment by Turtlelord26** [comment]
Also to note, your changelog mentions Flamethrower Peripherals but that commit isn't in this pull. Also it's not just classes, the entire New Player Guide is new to RC via this merge. Finally, I don't see anything about ASPRO-S Hackability in these changes.

**Review by Turtlelord26 — CHANGES_REQUESTED** [review]
By File and Item

#Basic Rules
-New Cha penalty - Functional Change - Testable ✔️
-Awareness Save - Functional Change - Testable ✔️

#Conditions
-New State: Lonely - Functional Change - Testable ✔️

#Glossary
-IO Ports - Nonfunctional Change ✔️
-Lonely - Nonfunctional Change ✔️

#New Player Walkthrough
-Document - Nonfunctional Change - Mostly Testable ❔

#Systemized Skills
-Document - Functional Change - Testable ✔️ - though slightly out of date and needs certain classes removed.

#Items
-Universal Translator - Functional Change - Testable ✔️

Engineer Processes
-IO Spell-out - Nonfunctional Change ✔️
-Cerberus Turret Specs - Functional Change - Testable ✔️
-Flamethrower peripheral - Functional Change - Testable ✔️

#Readme
-Version Bump - Nonfunctional Change ✔️
-New Director - ...Change. ✔️

Still need this point addressed: 
It is possible we should hold off on merging the New Player Walkthrough until it is a complete document that we could inflict upon have a new player try out. Marking as change request but mostly I want to see if there's a strong opinion on the matter. Default to cutting those changes from this merge.

Continuing Changelog Issues: 
Still mentions not-the-entire new player guide
Still mentions ASPRO-S but no changes to it in these commits.

**Comment by bleehu** [comment]
Perhaps the hacking ASPRO-S made it into R_C somehow already?
https://github.com/bleehu/Compound_X/blob/MH-version-b-0.0.7/CharacterCreation/Class-Specific%20Documentation/Engineer%20Processes.txt#L1022

I've modified the changelog outside of git to reflect the new player guide. I think we can send it in it's current form. I think it would be super helpful even if it's incomplete.

**Review by Turtlelord26 — APPROVED** [review]

**Comment by Turtlelord26** [comment]
Make it so

**Pull request merged**
