### PR TITLE
added Vorpal Rounds

### PR DESCRIPTION
**Pull request by bleehu**
Part 1 of 5 for Issue #130. Using MH lv 10 branch as a superbranch, will close the Issue when the proposed rounds are merged or rejected.

### CODE REVIEW

**Review by Turtlelord26 — CHANGES_REQUESTED** [review]
1. I know you don't generally like to handle typography in initial PRs but please fix the spelling of Vorpal; it hurts to look at.

2. As we are aiming for a soft sci-fi, we need at least semi-plausible reasons for our things working as described. So what makes these bullets extra effective specifically when they hit particularly vulnerable bits of anatomy?

**Comment by bleehu** [comment]
1. If you insist.

2. This was never explained to me. Scrap the round entirely?

**Comment by Turtlelord26** [comment]
We can try posing the question to the team and see if anyone comes up with something half-plausible.

**Comment by bleehu** [comment]
Is that still too hand-wavy?

**Comment by Turtlelord26** [comment]
Definitely getting there. I think I would like a phrasing that implies that the lack of locomotion is the result of fundamental design constraints rather than a mistake (at least, I read over-/under-equipped as mistakes). Maybe a phrasing more like 'the density of nanoweaponry precludes powerful locomotive capability'.

{While you're in there, there's a damage that should be a damages in line 459}

**Comment by bleehu** [comment]
How'zat?

**Review by Turtlelord26 — APPROVED** [review]
Still typoed :( but shipitable 👍

**Comment by Turtlelord26** [comment]
😃

**Pull request merged**
