### PR TITLE
bumped version number

### PR DESCRIPTION
**Pull request by bleehu**

### CODE REVIEW

**Comment by Turtlelord26** [comment]
Why does the version bump PR have 59 commits?

**Comment by bleehu** [comment]
Among other things, it deletes the human doc, which is a change that RC got that dev should not. My hunch is that this change has RC as a parent when I had intended it to have dev as the parent.

**Comment by Turtlelord26** [comment]
Does that mean this needs some doctoring before it gets reviewed?

**Comment by bleehu** [comment]
Probably doctored like you doctor a horse with a broken leg...

**Review by Reveraine — COMMENTED** [review]
I'm a little confused about this. 
While it's true the races are not ready for play, are you not merging them to dev?

**Comment by Turtlelord26** [comment]
Species are already in dev and not intended for deletion there. That's part of the reason this PR is messed up.

**Comment by bleehu** [comment]
We're not-not merging them to dev; this is a bad PR that is aborted because it's wrong heritage created that delta which would remove the Species work from dev.

**Pull request closed without merging**
